@hostname = c64.meatloaf.cc
@port = 80
@host = {{hostname}}:{{port}}
@path = /GAMES/
@image = CRILLI93.D64
@file = $

###
GET http://{{host}}/api/?p={{path}}&i={{image}}&f={{file}} HTTP/1.1

###
POST http://{{host}}/api/ HTTP/1.1
User-Agent: MEATLOAF CBM [20200923.01]
Content-Type: application/x-www-form-urlencoded

p={{path}}&i={{image}}&f={{file}}

###
POST http://{{host}}/api/ HTTP/1.1
User-Agent: MEATLOAF CBM [20200923.01]
Content-Type: application/x-www-form-urlencoded

p={{path}}&i={{image}}&f={{file}}

###
GET http://c64.meatloaf.cc HTTP/1.1

###
GET http://c64.meatloaf.cc HTTP/1.1
User-Agent: MEATLOAF CBM [20200923.01]
